"""empty message

Revision ID: 1094f7e88e19
Revises: 77dc2eedf8d9
Create Date: 2025-11-04 22:59:25.181834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1094f7e88e19'
down_revision = '77dc2eedf8d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('defect_solution', schema=None) as batch_op:
        batch_op.add_column(sa.Column('solution_name', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('defect_solution', schema=None) as batch_op:
        batch_op.drop_column('solution_name')

    # ### end Alembic commands ###
