"""empty message

Revision ID: 77dc2eedf8d9
Revises: 
Create Date: 2025-11-04 15:55:13.568297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77dc2eedf8d9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('defect', schema=None) as batch_op:
        batch_op.add_column(sa.Column('line_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'line', ['line_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('defect', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('line_id')

    # ### end Alembic commands ###
