"""empty message

Revision ID: c519a8bacd9d
Revises: dd4d727e1205
Create Date: 2025-11-06 13:40:40.148897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c519a8bacd9d'
down_revision = 'dd4d727e1205'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('line', schema=None) as batch_op:
        batch_op.add_column(sa.Column('daily_target', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('weekly_target', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('monthly_target', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('line', schema=None) as batch_op:
        batch_op.drop_column('monthly_target')
        batch_op.drop_column('weekly_target')
        batch_op.drop_column('daily_target')

    # ### end Alembic commands ###
