"""empty message

Revision ID: dd4d727e1205
Revises: 1094f7e88e19
Create Date: 2025-11-05 00:13:20.337664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd4d727e1205'
down_revision = '1094f7e88e19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('defect_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('commit', sa.Text(), nullable=True))
        batch_op.drop_column('notes')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('defect_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('commit')

    # ### end Alembic commands ###
